### ISSUE TITLE
Renaming a Tango doesn't show in directory

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#26]
After creating a Tango and updating, its name appears in the directory.

Then, after changing the name and updating, the new name is correctly stored, but the old one appears in the directory.

**Comment by adamzerner** [comment]
This has been fixed by PR #20. For the Tango's you've created prior to the fix won't see the fix though, and I don't think you'll be able to delete them either, sorry. You'll have to delete your account and create a new one (click the thing in the top right, and then just click the Facebook/Twitter/Google button again and you'll start fresh).

**Comment by adamzerner** [comment]
If you wouldn't mind, could you confirm that you don't still have this problem after deleting your account and creating a new one?

**Comment by jrmyp** [comment]
Done, renaming Tangos now works fine.
