### ISSUE TITLE
All Tangos disappear after updating Sims

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#31]
Saved Tangos disappear from My Tangos every time I click the Save button in My Sims.

It doesn't matter whether Sims were loaded or not in the deleted Tangos, nor if any changes have actually been made in My Sims.

**Comment by adamzerner** [comment]
Unable to replicate. It's probably because I've been making changes and it wasn't really stable (ie. I'm not sure what the problem was, but I think involves the changes I had been making). It is stable now though. You may have to delete your account and create a new one.

![sdfsaf](https://cloud.githubusercontent.com/assets/3144254/10626458/40e18d56-777d-11e5-812f-8e0ae912cab5.gif)
