### ISSUE TITLE
Confusing UI when accessing a private Tango when logged out

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#42]
Here is what I tried:
* log in, create a Tango
* copy its URL
* log out and access the URL

What I get is an "empty" interface, where all I can do is edit the title, and upon clicking "Update Tango", a waiting pointer appears, and I get redirected to the home page, still waiting. The actual Tango I tried to access is unchanged.

**Comment by adamzerner** [comment]
1) When you're logged out, you shouldn't be able to access a private Tango.

2) There is indeed a bug in the front end authorization code. It's because of a bug in UI Router - http://stackoverflow.com/questions/33059308/ui-router-how-should-you-prevent-tostate-from-showing-while-youre-checking-aut. Given that the size of this project, I don't think it's worth the effort to work around it.

**Comment by adamzerner** [comment]
1) When you're logged out, you shouldn't be able to access a private Tango.

2) There is indeed a bug in the front end authorization code. It's because of a bug in UI Router - http://stackoverflow.com/questions/33059308/ui-router-how-should-you-prevent-tostate-from-showing-while-youre-checking-aut. Given that the size of this project, I don't think it's worth the effort to work around it.
